AVD6.0:
  platformName: 'Android'
  platformVersion: '6.0'
  deviceName: 'emulator-5554'
  noReset: 'true'
  autoAcceptAlerts: 'true'
  autoGrantPermissions: 'true'
  command-timeout: '60'
  app: './apk/ApiDemos.apk'

LGG2:
  platformName: 'Android'
  platformVersion: '4.4.2'
  deviceName: 'IMDAG_G2'
  noReset: 'false'
  autoAcceptAlerts: 'true'
  autoGrantPermissions: 'true'
  command-timeout: '60'
  app: './apk/ApiDemos.apk'
